# SPDX-FileCopyrightText: 2023 peepo.world developers
#
# SPDX-License-Identifier: EUPL-1.2

version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: greenhouse
    ports:
      - 5432:5432
    volumes:
      - ./max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql
      - database-data:/var/lib/postgresql/greenhouse-data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database-data:
